### ISSUE TITLE
Enforce english language

### ISSUE THREAD

**Issue by jeffdefacto** [facebook/RapiD#10]
RapiD only has English language support currently so it should always open in English. Users are unable to set this on their own.

**Comment by gaoxm** [comment]
I checked the language behavior on RapiD, which is inherited from iD. Basically it tries to use the browser's top language preference with a best effort and falls back to whatever translation language is available:

![image](https://user-images.githubusercontent.com/7350578/62242429-24d08100-b3a9-11e9-88f7-2c6dab095d2d.png)

So right now this doesn't bother RapiD's usability much, but an explicity language setting feature is good to have. It would be even better if iD can build this so that we can pick it up by merging :).

**Comment by bhousel** [comment]
This is stale, tracked more on #206..
I did add a workaround to always have the English strings loaded.
