### ISSUE TITLE
Disabling and renabling Mapillary loses my current image position

### ISSUE THREAD

**Issue by cbeddow** [facebook/Rapid#1048]
### Description

If I enable Mapillary then click an image, I get a marker with current image position and camera angle

If I disable Mapillary by unchecking the box, then the Mapillary image viewer remains open, but the layer disappears.

Then when I re-enable, the Mapillary current image icon is gone. Navigation in the images does not bring it back. 

Clicking on a new images does not bring it back either. So the result is I can never see again where the image I am viewing is located.

### Version

2.0.3

### What browser are you seeing the problem on? What version are you running?

Chrome 115.0.5790.173 64-bit

### The OS you're using

Windows 11

### The browser URL at the time you encountered the bug

https://rapideditor.org/edit#background=EsriWorldImageryClarity&datasets=fbRoads,msBuildings&disable_features=boundaries&map=20.00/32.71728/-117.16386&photo=mapillary/331402731741396&photo_overlay=mapillary

**Comment by Bonkles** [comment]
This issue had a very simple fix- when we record data for the scene, each layer is in charge of keeping track of what's hovered, what's selected, etc. 

We were telling the renderer 'hey, go get the current class information for item of ID 1234567890, see if it's being hovered or if it's selected!'. 

And the answer was always 'no data' because the hover/select data was inside a string-indexed object, not a number-indexed object. Initial click worked okay, but if the user navigated away, or used the arrows to click left and right, our current selection didn't 'stick'. 

Vid showing it working now: 
https://github.com/facebook/Rapid/assets/1887955/2e406ffe-8e22-4450-a2b9-8c6404348249
