### ISSUE TITLE
Dataset not showing up in Rapid 2.1 when opened through Tasking Manager

### ISSUE THREAD

**Issue by SeanWhitcomb** [facebook/Rapid#1070]
### Description

I have created a set of tasks to map buildings using the OSM US Tasking Manager. It is set up to use the Scottsdale Building Footprints dataset. It previously worked fine, but the new version of Rapid does not show any of the features in the dataset. 

When I use the Rapid editor directly, I am able to add the Scottsdale buildings dataset and edit just fine. But if I open the same area through a task in the Tasking Manager, there are no buildings visible.

### Version

2.1

### What browser are you seeing the problem on? What version are you running?

Firefox 116.03

### The OS you're using

Win 11

### Steps to reproduce

Open a task from project 445 in the OSM US Tasking Manager: https://tasks.openstreetmap.us/projects/445/tasks

(This project is in draft mode, so it can't be accessed by other people.)

Going directly to the URL also leads to the same issue.

### The browser URL at the time you encountered the bug

https://rapideditor.org/edit?#background=Bing&datasets=602e0a13644a4daead72094e49d238ff&gpx=https://tasks-backend.openstreetmap.us/api/v2/projects/445/tasks/queries/gpx/%3Ftasks%3D27&map=15.00/33.5689/-111.9177&presets=building

**Comment by Bonkles** [comment]
Root cause determined! 

The `rapid_context.js`  in v1 expected us to pass in a DOM string with just the raw XML, which we'd then spin up a new DOMParser() to evaluate. 

We recently refactored our file fetching to rely on `fetch` instead of the various d3 helpers. This meant that the calling code had already very helpfully parsed the DOM string for us. 

The Rapid System in v2.1 _was still expecting to be passed a raw XML string_, when in fact it was being passed a pre-parsed DOM object. 
 
 As a result, we were trying to re-parse the parsed object, which of course failed, which meant the extent was unset, which meant that the `crop_bbox` we sent to the backend was malformed, which meant ... no data sent back to us. 
 
 THe fix was simply to remove the extra DOMParser() invocation at the top of the function.

**Comment by Bonkles** [comment]
Just for testing purposes, I delivered a test build if 2.1.1 to the cloud and stood up my own Scottsdale AZ HOT task within our local tasking manager. Verified that 2.1.0 repros the problem, but that the new 2.1.1 version fixes it: 

![image](https://github.com/facebook/Rapid/assets/1887955/1a92bc43-ba5e-4f38-a406-d846a1002b1f)
