### ISSUE TITLE
Conflicting crossing tags not being identified by validation

### ISSUE THREAD

**Issue by atiannicelli** [facebook/Rapid#1223]
### Description

When I click on a feater with crossing=unmarked and crossing:markings=lines I am not seeing a validation error pop up. I expected to see a validation error about the fact that this crossing has conflicting tags.### 

### Screenshots

![Screenshot 2023-11-16 at 1 24 38 PM](https://github.com/facebook/Rapid/assets/5851115/257a9cba-99b1-45bd-8c66-910036f58861)

### Version

2.2.0b

### What browser are you seeing the problem on? What version are you running?

Chrome v119.0

### The OS you're using

mac

### Steps to reproduce

Go to the link in the bug and make sure validation is turned on... Observe.

### The browser URL at the time you encountered the bug

https://rapideditor.org/rapid-test#background=Bing&datasets=fbRoads,msBuildings&disable_features=boundaries&id=w1103596452&map=21.93/41.68757/-87.65330

### The auto-detected useragent string for your browser (leave blank if you're manually filling this form out)

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36

**Comment by Bonkles** [comment]
Strongly suspect that since both the way and node in this case are `crossing=unmarked` my validation logic doesn't flag it, despite the fact that they have differing markings. 

I'll need to think about what kind of fixes we generate for this case. Three fixes, one for `set both to unmarked`, then two for `set to marked with crossing:markings=<nodemarkings>` and `set to marked with crossing:markings=<waymarkings>`

**Comment by bhousel** [comment]
A bunch has moved in the past month on the ambiguous crossing validator, and this junction is correctly flagged as a mismatch now.  Most of the code changes are attached to #1260 

<img width="625" alt="Screenshot 2024-01-02 at 2 40 13 PM" src="https://github.com/facebook/Rapid/assets/38784/bcd3b42c-902e-4c61-8972-e09e876e169a">
