### ISSUE TITLE
Automatically synchronize crossing line and node tags

### ISSUE THREAD

**Issue by cbeddow** [facebook/Rapid#1260]
### Description

- if I change a crossing node's value, like that it's a ladder marking, or crossing with signals, or raised, then I would expect the line attached to it to also inherit the changes. Also if the line has multiple nodes, changing one node changes all. A sort of chained event.

- and same, if I change the line's type, I should see the node change to match and inherit all values

^ I think right now if I draw a crosswalk line, set it as marked with ladder or something, and then accept the warning suggestion to connect it to a road it crosses, the new node created automatically does inherit. But if I then change the line or node once they exist, not sure they adopt each other's changes.

This could also be a suggested fix/warning for existing crosswalks, where they mismatch just say "use line tags" or "use node tags" and indicate if one is more detailed than the other maybe.

**Comment by bhousel** [comment]
These are great suggestions.. 
I've been doing a bunch of testing over the past few days and I agree that keeping the crossing node tagging in sync with the crossing way tagging is currently painful.

> This could also be a suggested fix/warning for existing crosswalks, where they mismatch just say "use line tags" or "use node tags" and indicate if one is more detailed than the other maybe.

Yes, this was the intent behind #1141 / #1204 "ambiguous crossing" validation.  I think this new validation is mostly working, but just want to make sure it is easy for users to understand.

Aside from that, I also see a lot of these kinds of upgrades being suggested to add `crossing:markings` to existing crossings.  As a quick improvement, I've changed the code so that now these will only be shown on the way and _not_ the node.   The "ambiguous crossing" validator can take care of making sure the node and way have consistent tagging, so we don't need to raise each of these issues twice for each crossing.

<img width="1006" alt="Screenshot 2023-12-11 at 12 33 44 PM" src="https://github.com/facebook/Rapid/assets/38784/6a552924-9111-4764-9090-049f59f2a381">

cc @1ec5 because we were just talking about this earlier today.

**Comment by tordans** [comment]
@bhousel I was testing this feature. Do I understand this correctly, that right now the line wins over the node? As in, if there is a diff, the line-tags are suggested to be applied to the node.
I wonder if this is actually the best case. At least in my areas the notes where there first and have better tagging than the lines. At least that is my gut feeling. 
Could the suggestion maybe be both way? Like "Apply node to line" and "Apply line to node" as two actions?


---

Something different: Is there anything rapid special in this code that would prevent it from being reused in iD?

**Comment by bhousel** [comment]
> @bhousel I was testing this feature. Do I understand this correctly, that right now the line wins over the node? As in, if there is a diff, the line-tags are suggested to be applied to the node.
> I wonder if this is actually the best case. At least in my areas the notes where there first and have better tagging than the lines. At least that is my gut feeling.
> Could the suggestion maybe be both way? Like "Apply node to line" and "Apply line to node" as two actions?

What happens now is that if there is any conflict between tagging on the line or node, it presents the all the different options.  The "line wins over the nodes" option is the default one, but users can pick from any of them.  One thing we don't do yet is let the user see the effects of what picking each option means, and I'd like to improve this.  The tag diff that is shown is the "line wins" case.

We used to have options "keep line tags" or "keep node tags" but this ended up being kind of confusing.   Consider also, situations like with one line and multiple nodes all in conflict (like you might find at a dual carriageway crossing).  

Here's an example:
<img width="778" alt="Screenshot 2023-12-18 at 11 21 37 PM" src="https://github.com/facebook/Rapid/assets/38784/e7d098ab-091d-4872-9094-212fdabe618a">


> Something different: Is there anything rapid special in this code that would prevent it from being reused in iD?

The iD and Rapid code are pretty different nowadays, but I can't think of anything specific that would prevent them from reusing our code to do the crossing synchronization.

**Comment by tordans** [comment]
> One thing we don't do yet is let the user see the effects of what picking each option means, and I'd like to improve this. The tag diff that is shown is the "line wins" case.

Thanks, I did not notice the other options at first. And I agree, the fact that diff is only for one option is not ideal. This is more confusing, because the diff section does not state which option it belongs to. I created https://github.com/facebook/Rapid/issues/1367 to track this outside this closed issue.
