### ISSUE TITLE
Modifying properties of curbs strips connected crosswalk of most of its tags.

### ISSUE THREAD

**Issue by mxxcon** [facebook/Rapid#1268]
### Description

Curb node 11418980879 is connected to crosswalk way 1231253214 which has tags:
```
crossing=traffic_signals
footway=crossing
highway=footway

```
and it looks like this
![image](https://github.com/facebook/Rapid/assets/847140/f6fd880f-4b3b-4878-a7e5-33b8acd611c0)
If I modify any property of that curb, the mentioned crosswalk suddenly loses `crossing=traffic_signals` tag
```
footway=crossing
highway=footway
```
And it looks like 
![image](https://github.com/facebook/Rapid/assets/847140/46bf60ef-954e-4126-8b1d-19b862c83df5)

This problems exist on 2.2 and this canary build too.

### Version

2.2.0

### What browser are you seeing the problem on? What version are you running?

Chrome v121.0

### The OS you're using

win

### Steps to reproduce

1. modify any tag of a curb
2. connected crosswalk loses tags

### The browser URL at the time you encountered the bug

https://rapideditor.org/canary#background=EsriWorldImagery&datasets=fbRoads,msBuildings&disable_features=boundaries&id=n11418980879&map=20.92/40.59189/-73.93729

### The auto-detected useragent string for your browser (leave blank if you're manually filling this form out)

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36

**Comment by bhousel** [comment]
Thanks for the report @mxxcon  - It looks like the crossing-tag-sync code was running in some situations when it shouldn't.  

If the user removes the crossing tags from the junction node, yes we want to sync that removal to the parent way - but if the user is just touching the kerb which has no crossing tags, we shouldn't try push "no crossing tags" up to the way.  

I fixed things so that it will only try a sync if a crossing tag was actually involved in what the user did.

I just published a v2.2.1 patch release on rapideditor.org that includes this fix.
