### ISSUE TITLE
Keyboard shortcut keys are shown as letters instead of keys

### ISSUE THREAD

**Issue by mxxcon** [facebook/Rapid#1272]
### Description

If I mouse-over any button that has a keyboard shortcut, it's shown as individual letters rather than keys.

Happens in Firefox, Chrome and Edge.

### Screenshots

![image](https://github.com/facebook/Rapid/assets/847140/868e78a1-a2ba-4b74-8591-d7c0f0d7bb29)
![image](https://github.com/facebook/Rapid/assets/847140/32c699a3-4389-48ad-803f-468b9706528c)

### Version

2.2.1

### What browser are you seeing the problem on? What version are you running?

Chrome v121.0

### The OS you're using

win

### Steps to reproduce

Mouse-over any button that has a shortcut tooltip.

### The browser URL at the time you encountered the bug

https://rapideditor.org/edit#background=Bing&datasets=fbRoads,msBuildings&disable_features=boundaries&id=w265042574&map=20.00/40.74569/-73.98640

### The auto-detected useragent string for your browser (leave blank if you're manually filling this form out)

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36

**Comment by bhousel** [comment]
Haha interesting - probably #1261 did this 🤔 
It's probably related to how the code does a slightly different thing on Windows to present <kbd>Ctrl</kbd> instead of <kbd>⌘ Cmd</kbd> .

<img width="295" alt="Screenshot 2023-12-27 at 1 33 12 PM" src="https://github.com/facebook/Rapid/assets/38784/8314ece3-64d4-4c3b-9f61-2d47fffb0dc8">
