### ISSUE TITLE
Choose second option in validation, but it doesn't do the right thing.

### ISSUE THREAD

**Issue by atiannicelli** [facebook/Rapid#1298]
### Description

if I pick the second option in the validation dialog then it does what the first option was.
The second picture is after choosing the second (unmarked) option.

### Screenshots

![image](https://github.com/facebook/Rapid/assets/5851115/371b35d6-3fb4-42d1-a538-e52aed118690)
After choosing the _second_ option....
![image](https://github.com/facebook/Rapid/assets/5851115/764f6ddf-6169-456f-8f39-6ab2e9691065)

### Version

2.2.4

### What browser are you seeing the problem on? What version are you running?

Chrome v120.0

### The OS you're using

mac

### Steps to reproduce

Create a feature with the following tags:

crossing=unmarked
crossing:markings=yes
footway=crossing
highway=footway

then when the validator pops up choose the "unmarked" option

### The browser URL at the time you encountered the bug

https://rapideditor.org/edit#background=Bing&datasets=fbRoads,msBuildings&disable_features=boundaries&id=w1231921570&map=22.07/51.47452/-0.01243

### The auto-detected useragent string for your browser (leave blank if you're manually filling this form out)

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36

**Comment by atiannicelli** [comment]
I also noticed today that the validator seems to be very slow. It takes many seconds for it to update to either flag a feature that has an issue or clear the validation issue after fixing the issue. I can get a video if you want.

**Comment by bhousel** [comment]
> crossing=unmarked
> crossing:markings=yes
> footway=crossing
> highway=footway

Thanks again, this was a good catch!  This mismatch between `crossing:markings=yes` and `crossing=unmarked` was throwing off the `inferCrossingType` function.  

Previously we were only looking for "interesting" values of `crossing:markings`, then falling back to whatever the `crossing` value contained.  This means that in a mismatch situation, it might end up choosing the wrong tag to apply when the user clicks the fix button.

I changed this code so that it now properly considers the `crossing:markings` 'yes' and 'no' values too, before falling back to looking at the `crossing` tag.

**Comment by bhousel** [comment]
> I also noticed today that the validator seems to be very slow. It takes many seconds for it to update to either flag a feature that has an issue or clear the validation issue after fixing the issue.

As an aside, I'm thinking of ways to move more of the validation code and tile fetching into web workers (#297).   As we add more complex validation logic, it is going to affect the performance.  Moving this work off the main thread will help a lot.  This is a big lift, but I've been making changes in the code over the past year to make background work more possible.

In any browser the validation can be slow around parts of the map with a lot of features.  But if you're using Safari, I think the performance might be worse because we [polyfilled `requestIdleCallback()`](https://caniuse.com/requestidlecallback) .  This means that, in Safari, the code doesn't run during idle times and it might be interrupting what the user is doing.
