### ISSUE TITLE
Road flagged as unreachable, but it is reachable

### ISSUE THREAD

**Issue by atiannicelli** [facebook/Rapid#1302]
### Description

I'm not sure what is causing it but I am getting an error that "main street is unreachable" but from everything I can see it looks fine.

### Screenshots

![Screenshot 2024-01-19 at 10 39 11 AM](https://github.com/facebook/Rapid/assets/5851115/22b06e03-905b-4778-b573-c0314b8f76ef)

### Version

2.2.4

### What browser are you seeing the problem on? What version are you running?

Chrome v120.0

### The OS you're using

mac

### Steps to reproduce

open rapid at w435336150 and look at the error.

### The browser URL at the time you encountered the bug

https://rapideditor.org/edit#background=Bing&datasets=fbRoads,msBuildings&disable_features=boundaries&id=w435336150&map=20.37/42.03341/-87.74772

### The auto-detected useragent string for your browser (leave blank if you're manually filling this form out)

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36

**Comment by atiannicelli** [comment]
Also, I noticed that the "Ignore This Issue" option does nothing.

**Comment by bhousel** [comment]
Good catch!  I stepped through the code with the debugger, and it looks like this is happening because Main Street here is tagged with `oneway=-1`.  This is a valid method in OSM to tag a oneway road that is drawn in the opposite direction of the direction of travel.  

The problem is that our `impossible_oneway` code has some wrong assumptions that the way is drawn in the direction of travel.  So code like this to determine `isFirst` has it backwards.  (it's actually last)

https://github.com/facebook/Rapid/blob/37ab4ebeeea76c717c8621a76271c9b2babca8a2/modules/validations/impossible_oneway.js#L79-L81

That means that instead of looking at the beginning of this part of Main Street to decide whether a user can enter it, it's looking at the wrong end and finding this, and concluding "I can't enter here":

<img width="264" alt="Screenshot 2024-01-19 at 11 00 37 AM" src="https://github.com/facebook/Rapid/assets/38784/f21d0572-e314-41c1-995d-93e5ea8b14df">
<img width="152" alt="Screenshot 2024-01-19 at 11 00 53 AM" src="https://github.com/facebook/Rapid/assets/38784/38d27ec2-d199-4a30-b585-c1592171a478">
