### ISSUE TITLE
Imagery selection has out of sync hover selected states

### ISSUE THREAD

**Issue by tordans** [facebook/Rapid#1378]
### Description

Video:

https://github.com/facebook/Rapid/assets/111561/d2613fdb-e347-435f-9399-036841b45a6d

The blue highlighting is out sync where something has a blue background but is not selected:

<img width="336" alt="image" src="https://github.com/facebook/Rapid/assets/111561/a981fa9f-ed4d-4e40-9567-85600d481e0f">

### Version

canary

### Steps to reproduce

See video

### The browser URL at the time you encountered the bug

https://rapideditor.org/canary#map=17.85/52.70497/13.88678&background=EsriWorldImagery&datasets=fbRoads,msBuildings&disable_features=boundaries

**Comment by bhousel** [comment]
I think what you might be seeing with the hover states is #1233 ? 
This is a behavior we inherited from the iD code, and it is confusing to people.  
The blue highlights will both show the **current** imagery and also the **previous** imagery - Users can toggle between these two sources by pressing the <kbd>⌘B</kbd> shortcut .

I will check to see how Wayback fits in with this - I haven't tested it, so there might be a bug..

**Comment by bhousel** [comment]
I thought about this more and decided to just remove the `.switch` class for the previously used imagery, since this looked weird and was causing users to think that something was broken on multiple occasions.

Now the 'last used' imagery just looks like any other inactive imagery source in the list.  

Users can still use <kbd>⌘</kbd><kbd>B</kbd> shortcut to toggle between current and last used, which we do explain in the tooltip and on the keyboard shortcuts screen.
