### ISSUE TITLE
Keep-it-right validator is showing way over water alerts even with a ford node present

### ISSUE THREAD

**Issue by jjiglesiasg** [facebook/Rapid#1459]
### Description

Activating the validator "Keep-it-right" give alerts for way over waterway even when there is a Ford Tagged connecting Node is present.

### Screenshots

![Screenshot (217)](https://github.com/facebook/Rapid/assets/22849578/7b77e86e-d918-4f5d-9c77-f8d70c43f68a)

### Version

2.3.1

### What browser are you seeing the problem on? What version are you running?

Version 125.0.2535.85 (Official build) (64-bit)

### Steps to reproduce

Open any place and look for way over waterway intersection

### The browser URL at the time you encountered the bug

No URL for Rapid in App Mode

**Comment by bhousel** [comment]
It looks like it might be this issue:
https://github.com/keepright/keepright/issues/60
(KeepRight doesn't seem to be actively maintained anymore, so I'd not expect a fix for it)

On the Rapid side, we don't have control of the KeepRight detections, but we do control which ones we show to the users, so we could definitely ignore some of the detections that don't make sense today.

**Comment by bhousel** [comment]
I just checked this issue and I'm not seeing the KeepRight warning anymore when I look at n11554756216

https://rapideditor.org/rapid#map=19.22/-16.77805/-66.37389&background=Bing&datasets=fbRoads,msBuildings&disable_features=boundaries&id=n11554756216

I'm not sure whether KeepRight fixed something on their end, or perhaps the issue was fixed sometime after the issue was first detected (IIRC, KeepRight refreshes their dataset weekly).  Either way I'm closing now since it seems fixed.
