### ISSUE TITLE
Areas and Lines are a little Broken in Tutorial

### ISSUE THREAD

**Issue by tannerwuster** [facebook/Rapid#1527]
### Description

- When adding **playground** to the area section of the tutorial, the dialog tutorial box obstructs the editing of the area. This can be fixed if you zoom browser out to 110%
- The **endpoint** that we need to drag is obstructed by the tutorial dialog box  

### Screenshots

![Screenshot 2024-08-28 at 15 08 09](https://github.com/user-attachments/assets/8d4b9843-03e4-4e08-9af6-bc2ff2117765)
![Screenshot 2024-08-28 at 14 57 50](https://github.com/user-attachments/assets/5e9ac7e4-4ac2-4179-a10c-1725b95ea8a6)

### Version

Canary 2.3.2

### What browser are you seeing the problem on? What version are you running?

Chrome v119

### The OS you're using

MacOS 14.1.1

### Steps to reproduce

Go through the tutorial until you get to Areas and Lines 

### The browser URL at the time you encountered the bug

https://rapideditor.org/canary#map=20.00/10.11413/76.49622&background=Bing&datasets=fbRoads,msBuildings&disable_features=boundaries&id=w800462434

**Comment by bhousel** [comment]
Thanks, I'll check this.. I think those cut out boxes are supposed to be defined as Extents , so they should really stay a consistent size.

**Comment by bhousel** [comment]
Oh it's probably this:

https://github.com/facebook/Rapid/blob/f26a9b854c4545b177b1e5d37b92375ed717725a/modules/ui/intro/UiCurtain.js#L80-L89

Since #1497, the sidebar will remember it's width, that might affect the curtain math 🤔 
(I also noticed that manually resizing the window will trigger the resize and fix the curtain placement).

Fortunately I did build "some kind of UISystem resize event" as part of #1497 so I'll switch the curtain over to using it! 😁

**Comment by bhousel** [comment]
It was a bit more than just the resize event, but that was helpful that we can listen to a better event now.

The issue was that 
 - We were caching rectangles for the map size and container size, and these things could
   be off by a little bit after the user resizes or the sidebar changes size, so we don't
   cache them anymore, we just call `getBoundingClientRect()` at the time we need the rectangle
    
I also fixed how we treat `revealExtent`:
 - These were previously just treated as rectangles, which would be wrong when
   the map rotates. This wasn't too much of an issue, because we didn't ask the
   user to rotate the map during the steps where we would reveal an Extent.
 - But now we treat them as polygons and project each corner, so they can
   handle being rotated and resized much better than before.

https://github.com/user-attachments/assets/095dcfec-ef17-4451-80b6-4953205e063c
