### ISSUE TITLE
Keyboard shortcuts trigger unwanted appearance of sidebar which remains covering map.

### ISSUE THREAD

**Issue by Numbergod** [facebook/Rapid#1562]
### Description

Appears to be related to Sidebar "fixes" #1497.

I usually have the sidebar hidden (the button for this has now been removed.  The keyboard shortcut works, briefly)

Upon selecting an item via mouse click and pressing a keyboard shortcut, the sidebar now pops out and stays there.

This is undesirable behavior.  There now appears to be no way to hide the sidebar until specifically requested to be shown.
This slows operation significantly.  Is there a way of stopping this behaviour?  

### Version

2.4.0

### What browser are you seeing the problem on? What version are you running?

Chrome Version 109.0.5414.120 (Official Build) (64-bit)

### The OS you're using

Windows

### Steps to reproduce

As described above.

### The browser URL at the time you encountered the bug

https://rapideditor.org/edit#map=17.80/-43.29839/172.20012&background=LINZ_NZ_Aerial_Imagery&datasets=ef9136b079e24bbfb432be9bbdd246ff&disable_features=traffic_roads,service_roads,paths,indoor,landuse,boundaries,water,rail,pistes,aerialways,power,past_future,others&poweruser=true

**Comment by eneerhut** [comment]
You can also click on the edge of the sidebar to close it. Not sure if it looks slightly different on Windows.
<img width="397" alt="image" src="https://github.com/user-attachments/assets/1f1ecbfc-0e15-427e-82fe-5fdf00db78aa">

Is your preferred behavior that the sidebar appears briefly so that you can select and modify tags before disappearing again?
