### ISSUE TITLE
Shift+D toggles OSM data instead of disconnecting objects

### ISSUE THREAD

**Issue by emersonveenstra** [facebook/Rapid#1628]
### Description

Shift+D used to disconnect selected objects, now it toggles OSM data, which should be Shift+O

PS: I know that just hitting d will disconnect objects, but either way Shift+D is not documented as the shortcut to hide OSM data

### Version

canary

### Steps to reproduce

1. Find two connected objects
2. Select the connecting node
3. Press Shift+D
4. OSM data disappears

### The browser URL at the time you encountered the bug

https://rapideditor.org/canary#map=20.73/42.99873/-84.17044&background=Bing&datasets=fbRoads,msBuildings&disable_features=boundaries&id=w775857665

**Comment by bhousel** [comment]
Hey @emersonveenstra thanks for reporting - this was intentional..

In the past (and still now) any of the non-shift keys will also match an unused shift-key.  So like you discovered, <kbd>Shift</kbd>+<kbd>D</kbd> did happen to Disconnect just as well as plain <kbd>D</kbd>.  Previously we did not use the shift-keys for much or even tell the user about this - I think the only one was <kbd>Shift</kbd>+<kbd>R</kbd> to toggle Rapid layer.

But we've received a bunch of feedback that mappers want to be able to toggle layers easier.  For example when mapping sidewalks, a user might want to toggle on streetview imagery to verify a curb cut, and then toggle it off.  The same applies to the Rapid data, the OSM data, the Notes, etc.

So we're trying to establish a convention that <kbd>Shift</kbd>+<kbd>Whatever</kbd> will toggle layers:

<kbd>Shift</kbd>+<kbd>D</kbd> toggle all the layers (show only background)
<kbd>Shift</kbd>+<kbd>O</kbd> toggle OSM
<kbd>Shift</kbd>+<kbd>N</kbd> toggle OSM Notes
<kbd>Shift</kbd>+<kbd>R</kbd> toggle Rapid
<kbd>Shift</kbd>+<kbd>M</kbd>  toggle Mapillary
<kbd>Shift</kbd>+<kbd>S</kbd>  toggle Bing streetside
<kbd>Shift</kbd>+<kbd>K</kbd>  toggle Kartaview

#778, #1400, #1578, #1592, #1594, #1606 track this stream of work.

Let me know what you think!  If some of these new layer-toggling shortcuts are inconvenient, we want to know.

I did update the Keyboard Shortcuts screen to include the new key shortcuts:

<img width="766" alt="Screenshot 2024-11-28 at 8 48 57 AM" src="https://github.com/user-attachments/assets/67144041-bcb6-42e6-88a4-83dd27d51df4">

**Comment by emersonveenstra** [comment]
Makes sense, i'm fine with it, just wanted to make sure it was intentional 👍
