### ISSUE TITLE
Pixi error when trying to fix an invalid polygon

### ISSUE THREAD

**Issue by emersonveenstra** [facebook/Rapid#1636]
### Description

Deleting nodes from https://www.openstreetmap.org/way/1338972960 locks up the editor with the following error:
```
MeshPipe.ts:146 Uncaught TypeError: Cannot set properties of undefined (setting 'texture')
    at MeshPipe.updateRenderable (MeshPipe.ts:146:30)
    at RenderGroup.updateRenderable (RenderGroup.ts:306:66)
    at updateTransformAndChildren (updateRenderGroupTransforms.ts:148:25)
    at updateTransformAndChildren (updateRenderGroupTransforms.ts:140:13)
    at updateTransformAndChildren (updateRenderGroupTransforms.ts:140:13)
    at updateTransformAndChildren (updateRenderGroupTransforms.ts:140:13)
    at updateTransformAndChildren (updateRenderGroupTransforms.ts:140:13)
    at updateRenderGroupTransforms (updateRenderGroupTransforms.ts:38:44)
    at RenderGroupSystem._updateRenderGroups (RenderGroupSystem.ts:190:9)
    at RenderGroupSystem.render (RenderGroupSystem.ts:70:14)
_draw	@	GraphicsSystem.js:507
_tick	@	GraphicsSystem.js:195

```

I can always reproduce it, but it's inconsistent when it happens, sometimes it does it while deleting nodes, and sometimes it does it when drawing a new line inside it

### Screenshots

![Screenshot 2024-12-03 at 20 05 10](https://github.com/user-attachments/assets/9f7b8118-df3d-4091-ace9-eef504b10f6b)

### Version

canary

### Steps to reproduce

1. Edit https://www.openstreetmap.org/way/1338972960
2. Delete the two nodes that are connected twice, and then quickly delete the ones in the middle (as if you were going to make it a multipolygon)
3. Create a new line and trace the middle wood area
4. It should freeze with the above error

### The browser URL at the time you encountered the bug

https://rapideditor.org/canary#map=18.45/42.12378/-111.92132&background=Bing&datasets=fbRoads,msBuildings&disable_features=boundaries&id=w1338972960

**Comment by bhousel** [comment]
This was indeed a weird bug, but I added a workaround in fd253a9 that seems to avoid the crashiness.

For background - we create the partial filling of the polygons by drawing lines inside them, then converting those lines into a mesh, and using that mesh for masking and hit testing the polygon.  (We do this because historically you could not hit test a line in Pixi - this has changed with recent versions, so maybe we don't need to do this anymore).

Apparently if the size of this mask changes from >200 vertices to ≦200 vertices , or vice versa, it can cause the mask to either get buggy, or go missing and cause the crash.

The magic 200 vertex number corresponds to a polygon with about 25 points in a single ring - this depends a bit on the path it takes and how complicated the line is, and if there are holes or inners, that will affect the count too.  So in the case of the above polygon, if you start deleting points until is is down to 25 points, boom! 💥 

We can investigate this more, but for now, we can detect this situation and just destroy and recreate the mask when the vertex count changes in this way.

The fix is in canary now, so that original link should be a good one to test with:
https://rapideditor.org/canary#map=18.45/42.12378/-111.92132&background=Bing&datasets=fbRoads,msBuildings&disable_features=boundaries&id=w1338972960

**Comment by emersonveenstra** [comment]
Works great, thanks for digging into it!
