### ISSUE TITLE
Minimap

### ISSUE THREAD

**Issue by Bonkles** [facebook/Rapid#485]
The minimap is now available using the hotkey forward slash `/`.  

The border has been updated a bit since v1 to soften its edges. 
![Image](https://user-images.githubusercontent.com/1887955/176240207-c20baaa3-93da-4f48-a64c-70c3cf66a79d.png)

Its operation is nearly the same as the old one- except that on pan, the viewfield doesn't update.

**Comment by bhousel** [comment]
> Its operation is nearly the same as the old one- except that on pan, the viewfield doesn't update.

I'd like to reopen this because I think having the viewfield rectangle stay fixed while the imagery moves under it is a pretty important feature - this allows the user to actually use the minimap to focus on some part of the map.
- [ ] fix viewfield rectange

### minimap v1

![minimap v1](https://user-images.githubusercontent.com/38784/216146320-7397ef8a-3e6f-4e3d-9cff-ef1d6d4c93ed.gif)

### minimap v2 beta

![minimap v2 beta](https://user-images.githubusercontent.com/38784/216146339-b8df3040-8a04-4de5-83d5-161f9da9df5f.gif)


Also noticing some minor visual issues:
- [ ] Locator overlay texture disappears sometimes?  It might be the code that removes locator overlay when map is loaded (this is a thing that should happen on the main map only)
- [ ] Actually we should probably scale down all the textures used?  This was an issue with the old map too.  Basically - we are displaying the overlay images that are designed for a normal sized map.  This image shows kind of what I mean:
<img width="689" alt="Screenshot 2023-02-01 at 2 46 29 PM" src="https://user-images.githubusercontent.com/38784/216149030-77441fe8-6b20-41d1-ae4b-10ac2793c983.png">

**Comment by bhousel** [comment]
> I'd like to reopen this because I think having the viewfield rectangle stay fixed while the imagery moves under it is a pretty important feature - this allows the user to actually use the minimap to focus on some part of the map.

I fixed this viewfield issue sometime around  3cbb638e3

**Comment by bhousel** [comment]
> * Actually we should probably scale down all the textures used?  This was an issue with the old map too.  Basically - we are displaying the overlay images that are designed for a normal sized map.

Fixed this in 061854d9d by just.. always rounding up to the next integer zoom instead of rounding to nearest.  This results in always fetching slightly sharper images than we need, rather than sometimes displaying blurry images. We'll see how this performs.
