### ISSUE TITLE
Ensure that Rapid works in WebGL1 context on older hardware

### ISSUE THREAD

**Issue by mxxcon** [facebook/Rapid#568]
### Description

On my computer Win10, Chrome 104 RapiD 2.0-alpha doesn't work and just gives me this screen.
![image](https://user-images.githubusercontent.com/847140/186811599-44383acf-c811-491c-ba53-0646b5b41779.png)

When I check dev console I see the following errors:

> Error: WebGL unsupported in this browser, use "pixi.js-legacy" for fallback canvas2d support.
>     at Renderer3.create (iD.js:82115:13)
>     at autoDetectRenderer (iD.js:82243:22)
>     at new Application2 (iD.js:82805:23)
>     at new PixiRenderer (iD.js:101011:19)
>     at map3 (iD.js:101185:19)
>     at Selection.call_default [as call] (iterator.js:4:12)
>     at render (iD.js:109266:74)
>     at iD.js:109408:11
> 

chrome://gpu/ shows

> Graphics Feature Status
> Canvas: Hardware accelerated
> Canvas out-of-process rasterization: Enabled
> Direct Rendering Display Compositor: Disabled
> Compositing: Software only. Hardware acceleration disabled
> Multiple Raster Threads: Enabled
> OpenGL: Enabled
> Rasterization: Hardware accelerated
> Raw Draw: Enabled
> Video Decode: Hardware accelerated
> Video Encode: Hardware accelerated
> Vulkan: Disabled
> WebGL: Hardware accelerated but at reduced performance
> WebGL2: Unavailable
> WebGPU: Hardware accelerated but at reduced performance

On Firefox 103.0.2 on the same computer the app works fine.

I don't know if you can improve compatibility to handle my hardware or better handle this error and display some message to users.

### Version

2.0-alpha

### What browser are you seeing the problem on? What version are you running?

Chrome v104.0.5112.102

### Steps to reproduce

Go to https://mapwith.ai/rapid-v2-alpha

### The browser URL at the time you encountered the bug

https://mapwith.ai/rapid-v2-alpha

**Comment by mxxcon** [comment]
I tried fiddling with those Chrome flags already and the output I posted in the first message is the best I could get to have the most features enabled.
There are no newer graphics drivers. This is a pretty old Dell Latitude E6420 with integrated Intel HD 3000 graphics card.

**Comment by mxxcon** [comment]
I just tried this on MS Edge and it gets a bit further, but still not usable
![image](https://user-images.githubusercontent.com/847140/187016816-2d3013f3-95ba-4584-9b01-1d985f6ac22e.png)
Edge dev tools console shows the following error:

>        Uncaught TypeError: Failed to execute 'texSubImage2D' on 'WebGLRenderingContext': parameter 9 is not of type 'ArrayBufferView'.
>     at AtlasResource.uploadItem (iD.js:95868:10)
>     at AtlasResource.upload (iD.js:95857:14)
>     at TextureSystem2.updateTexture (iD.js:81750:48)
>     at TextureSystem2.bind (iD.js:81670:16)
>     at AbstractBatchRenderer2.bindAndClearTexArray (iD.js:82527:23)
>     at AbstractBatchRenderer2.drawBatches (iD.js:82559:16)
>     at AbstractBatchRenderer2.flush (iD.js:82577:12)
>     at AbstractBatchRenderer2.stop (iD.js:82591:12)
>     at BatchSystem2.setObjectRenderer (improveOSM.js:42:30)
>     at BatchSystem2.flush (improveOSM.js:54:14)

edge://gpu/ shows:
> Graphics Feature Status
> Canvas: Hardware accelerated
> Canvas out-of-process rasterization: Disabled
> Direct Rendering Display Compositor: Disabled
> Compositing: Hardware accelerated
> Multiple Raster Threads: Enabled
> OpenGL: Enabled
> Rasterization: Unavailable
> Raw Draw: Disabled
> Video Decode: Hardware accelerated
> Video Encode: Hardware accelerated
> Vulkan: Disabled
> WebGL: Hardware accelerated
> WebGL2: Unavailable
> WebGPU: Disabled

Interestingly, https://webglsamples.org/aquarium/aquarium.html works on Edge(and Firefox), but not Chrome.

**Comment by bhousel** [comment]
Back from FOSS4G conference!  Today I'm trying to dig into this issue some more..  Thanks again for the detailed debugging information and for testing in several different browsers! 

Pixi does have a way to use WebGL's `failIfMajorPerformanceCaveat` flag before creating a context, but [from their docs](https://pixijs.download/release/docs/PIXI.settings.html#FAIL_IF_MAJOR_PERFORMANCE_CAVEAT), it looks like in v6+ this value is set to `false`, which I take to mean that it won't fail and will attempt to create a context anyway. 

Interestingly, Firefox seems to have [dropped support for this flag](https://bugzilla.mozilla.org/show_bug.cgi?id=1678652) as of around FF86, this is probably why you're able to use it on Firefox.

Some other interesting stuff I see in your output:
> WebGL2: Unavailable

and the error in edge:

>    Uncaught TypeError: Failed to execute 'texSubImage2D'
is the sort of thing I've seen before in a WebGL1 environment.

So my best guess about what's happening:
- Chrome won't give you a WebGL context even with the fail flag set to false
- Firefox will give you a WebGL(2?) context anyway, because it ignores the fail flag
- Edge will give you a WebGL1 context, but something in the AtlasTexture code is breaking because it's really written for WebGL2.

These are all slightly different issues - maybe the WebGL1/AtlasTexture thing we can do something about - but I do think some of it is outside our control and just related to your older device..

Still, I think for the beta release of RapiD, I'd like to try to make a fallback build that uses pixi-legacy canvas render and use that one if we detect a missing webgl context.

> Interestingly, https://webglsamples.org/aquarium/aquarium.html works on Edge(and Firefox), but not Chrome.
> Also https://demo.f4map.com works on Firefox and Edge, but on Chrome it complains about lack of WebGL

Are you able to run the examples here?  https://pixijs.io/examples/#
I'd expect these would either work or fail in similar ways to RapiD.

**Comment by mxxcon** [comment]
> Are you able to run the examples here? https://pixijs.io/examples/#

Most of the tests that I tried in Chrome seemed to work, or at least partially worked. I didn't do every single one since there are too many of them. Of the ones that I did try, a bunch looked slightly different compared to Firefox, and I think a couple looked incorrect in Firefox. But none of them errored out.

Let me know if you want me to try some specific examples there.

**Comment by bhousel** [comment]
> Let me know if you want me to try some specific examples there.

I was thinking about this a bit and I'm curious whether transparency of the canvas matters in your case?

Solid canvas:
https://pixijs.io/examples/#/demos-basic/container.js

Transparent canvas:
https://pixijs.io/examples/#/demos-basic/transparent-background.js

This is just a guess, but I'm wondering whether Chrome's issue is that it doesn't have a GPU accelerated compositor to blend the WebGL canvas with whatever is under it.  

In RapiD, we have the canvas set to transparent since earlier this year because we were showing slippy map tiles beneath it, but we don't need to do this anymore - we draw the tile layers in Pixi now for the past few months.

**Comment by mxxcon** [comment]
In Firefox and Chrome both tests look identical.
Solid canvas is 25 rabbit-bear things spinning on blue background with no apparent visual artifacts(except in Chrome CPU usage is almost 80%).
Transparent canvas looks the same in both browsers, 1 rabbit-bear thing spinning on grey grid background. CPU usage in slightly higher in Chrome than Firefox but decently low.

**Comment by cbeddow** [comment]
@mxxcon any success trying this again now?

**Comment by mxxcon** [comment]
Just tried in Chrome 108 and it now looks similar to how it looked in Edge in the 4th comment screenshot above.
Devtools console shows the following errors:
![image](https://user-images.githubusercontent.com/847140/205418847-5afdf396-1fda-492d-9907-4caac6e3bdc7.png)

**Comment by bhousel** [comment]
Thanks @mxxcon  - this might be good news?
If Chrome's behavior matches Edges, it means that you ended up with a WebGL1 context..
The WebGL1 TextureAtlas might be a thing we can fix.

**Comment by bhousel** [comment]
> Thanks @mxxcon - this might be good news?
If Chrome's behavior matches Edge's, it means that you ended up with a WebGL1 context..
The WebGL1 TextureAtlas might be a thing we can fix.

Hey @mxxcon - I recently made some changes in the Texture Atlas code that I'm hoping might improve Rapid's compatibility with WebGL1 contexts.

Whenever you get a chance, could you let me know if you are able to use the latest Rapid release on 
https://mapwith.ai/rapid ?

This latest version will say 2.0.2 down in the bottom right corner.

**Comment by mxxcon** [comment]
Seems to be working correct now in Firefox 111, Chrome 111.0.5563.148 and MS Edge 112.0.1722.39. 
Chrome dev tools don't show errors like it did in the past.
![image](https://user-images.githubusercontent.com/847140/231873953-a188ae69-883b-4448-96c2-c6719505fdb0.png)
👍

**Comment by bhousel** [comment]
> Seems to be working correct now in Firefox 111, Chrome 111.0.5563.148 and MS Edge 112.0.1722.39.
> Chrome dev tools don't show errors like it did in the past, only warnings and deprecation.

Thats great!  thanks for testing!
