### ISSUE TITLE
Make Kontur hosted OpenAerialMap mosaic available as an aerial layer

### ISSUE THREAD

**Issue by cbeddow** [facebook/RapiD#677]
### Description

See here for JOSM integration: https://josm.openstreetmap.de/wiki/Maps/Worldwide#OpenAerialMapMosaicbyKontur.io

**Comment by bhousel** [comment]
Closing here - it looks like it is now available as an overlay since we've updated editor-layer-index.
This means that when activated, the imagery will float over the basemap in areas where it's available.

<img width="838" alt="Screenshot 2023-02-15 at 3 32 02 PM" src="https://user-images.githubusercontent.com/38784/219147733-331ed232-49bf-45b0-a604-a429f6abc064.png">

Here there is some coverage of Pemba Island
https://mapwith.ai/rapid-v2-beta#background=Bing&datasets=fbRoads,msBuildings&disable_features=boundaries&map=10.34/-5.1309/39.7955
