### ISSUE TITLE
Square function bug on areas

### ISSUE THREAD

**Issue by Mapiate** [facebook/RapiD#682]
### Description

Using the Square function on areas either by right clicking or using the hotkey Q does not work as expected. There seems to be a delay and does not render until additional actions take place, like adding or deleting nodes, or moving the area. Trying to use the Square option again, is then disabled.

New Building where the Square function was used but did not show the new shape.
![image](https://user-images.githubusercontent.com/119600354/205063543-0db419de-2ecb-49f9-be35-a1aa75b179a6.png)

When using the Move function, the new shape then displays but leaves behind traces of the nodes.
![image](https://user-images.githubusercontent.com/119600354/205064560-c7b6e923-01c4-4ff9-80f8-e33d178e3874.png)

I was able to reproduce this consistently in Firefox and Chrome.

### Version

2.00-alpha.3

### What browser are you seeing the problem on? What version are you running?

Firefox v107.0

### Steps to reproduce

Create a new building.
Right click or use the Q hotkey to use the Square. 

### The browser URL at the time you encountered the bug

https://mapwith.ai/rapid-v2-alpha3#background=MAPNIK&datasets=fbRoads,msBuildings&disable_features=points,indoor,landuse,boundaries,rail,pistes,aerialways,past_future&id=w-5&map=19.00/43.41944/-71.95998

**Comment by Bonkles** [comment]
Thanks for the report! I'll add a little context here- after squaring the building the first time, RapiD's in-memory representation of the building has been updated to be square. When you right-click again, the square option isn't available because RapiD thinks the shape is square. 

This causes understandable user confusion, because RapiD  hasn't redrawn the shape to *look* square.  

If you were to hit the browser reload button and keep your changes, you would see the squared building get rendered correctly.

**Comment by Bonkles** [comment]
Update to the update- nope, square has the same bug that circularize, rotate, etc. all have right now. That is, until the fix we just pushed! 

Fixed in alpha 3.2 release that just went live.
