### ISSUE TITLE
UI suggest snapping, but no snapping occurs

### ISSUE THREAD

**Issue by mvexel** [facebook/RapiD#689]
### Description

In point (node) drawing mode, when hovering over the halo of an area feature, the UI suggests that a point drawn at that moment will snap to the area outline, however, the point appears in the interior, no snapping occurs.

https://user-images.githubusercontent.com/120452/205715211-5e2e25df-aeb9-4adb-9986-58e2f0fb0e0a.mov

### Version

2.00-alpha3

### What browser are you seeing the problem on? What version are you running?

Firefox 107 Mac

### Steps to reproduce

1. Enter point drawing mode
2. Hover over the halo of an area feature
3. Click to draw the point

### The browser URL at the time you encountered the bug

https://mapwith.ai/rapid-v2-alpha3#background=EsriWorldImagery&datasets=fbRoads,msBuildings&disable_features=boundaries&map=21.50/40.74004/-111.86053

**Comment by Bonkles** [comment]
Whew! Okay, some discussion here. 

First, I have just cleaned up the snapping as best as I can for the mapathon this friday (whoo). The renderer will no longer get confused about whether it is targeting a parent way or area during a node dragging operation. 

Note: Node snapping works a little funkily at the moment. I have filed #719 to track this. Basically, we need to rethink how we do our polygon rendering and targeting. There's more information there. 

For now, you should be able to snap nodes to ways as normal, and areas will only 'snap' once you hover over the area fill. Like so: 



https://user-images.githubusercontent.com/1887955/207694230-cd584afa-f573-4886-b18d-67bb110a68ae.mov



Downside- in wireframe mode, this means nothing is targetable! But that will get fixed in #719 as well.

**Comment by Bonkles** [comment]
Fixed in `d72e896fb9289e6695eec6f38d2a169f8c9d8ca1`. Incidentally this made the behavior of the fix for #702 even better- the way/area you're modifying will no longer 'flicker' as you drag the node around.
