### ISSUE TITLE
Thanks post-upload dialog disappears

### ISSUE THREAD

**Issue by mvexel** [facebook/Rapid#700]
### Description

After clicking "Upload", the "You Just Edited OpenStreetMap" dialog is visible in the background but immediately disappears when the uploading modal disappears. This only happens if you move the pointer onto the map canvas while the changeset is being committed.

https://user-images.githubusercontent.com/120452/205752622-5fd2e2e5-1eab-4763-8e18-5a025a4687a8.mov

### Version

2.00-alpha3

### What browser are you seeing the problem on? What version are you running?

Firefox 107 Mac

### Steps to reproduce

1. Make some map changes
2. Click "Save", add a changeset description, and click Upload
3. While the Uploading modal is visible, move the mouse pointer onto the map canvas

### The browser URL at the time you encountered the bug

https://mapwith.ai/rapid-v2-alpha3#background=Bing&datasets=fbRoads,msBuildings&disable_features=boundaries&map=19.82/42.55401/-114.56163

**Comment by mvexel** [comment]
Confirming that iD does not have this behavior. 

Also noting that this behavior does not occur when the RapiD Assist layers are completely turned off (`Shift-R`)

**Comment by Bonkles** [comment]
Yes, this has to do with the 'hover' mode that we put in for RapiD assist layers. As soon as you hover over something, it replaces the sidebar with the 'details' of the assist feature. 

That's why iD doesn't have this (no rapid features whatsoever) and that's why this actually isn't a regression from RapiD v1- same issue exists there. We need to come up with a better way to allow the save dialog to persist, but at least this isn't a regression.

**Comment by bhousel** [comment]
We turned off the hovering behavior a while ago, so I'm going to close this issue.
I think we probably do want to restore some kind of ability to hover over things and see what they are, but maybe flashing the sidebar is overkill.
