### ISSUE TITLE
F11 on Mac don't work.

### ISSUE THREAD

**Issue by atiannicelli** [facebook/RapiD#724]
### Description

When I press F11 is moves all windows away instead of full screen mode.

### Version

2.00-alpha.3.3

### What browser are you seeing the problem on? What version are you running?

Chrome v108.0

### The browser URL at the time you encountered the bug

https://mapwith.ai/rapid-v2-alpha3#background=MassGIS_2021_Aerial&datasets=fbRoads,msBuildings&disable_features=boundaries&map=21.00/42.65986/-71.13015

**Comment by divyansh21jain** [comment]
Hi @atiannicelli  you can also enter  "Control + Command + F" on Mac. 
I don't know but might be possible that in M1 macbook F11 is not taking us to full screen mode in chrome and other browsers also. 
Hope this helps.
Happy Coding !

**Comment by mvexel** [comment]
Is F11 explicitly mentioned anywhere in the Rapid UI?
I see https://github.com/facebook/RapiD/blob/8c2775276eaf0946686ad479543ea20343f413e3/data/shortcuts.json#L57 which may be relevant here.
On Mac it's generally Cmd-Ctrl-F (as @divyansh21jain mentioned) or Globe-F.

**Comment by bhousel** [comment]
I just restored the fullscreen keybindings, they were missing from the code that sets up the UI.

On my Mac, <kbd>F11</kbd> also is taken by the misson control shortcut to "show desktop".   (I think F11 to go full screen is a Windows convention).
But these do work:
* <kbd>Command</kbd><kbd>Control</kbd><kbd>F</kbd> 
* <kbd>Fn</kbd><kbd>F</kbd> 

So I think I'll adjust the shortcuts that show up on the help screen to remove the F11 option on Mac, since it's not likely to work there.


<img width="668" alt="Screenshot 2023-01-19 at 12 24 16 PM" src="https://user-images.githubusercontent.com/38784/213516214-91b79dd2-0bc0-45cb-8b50-9c46d284f2fa.png">
