### ISSUE TITLE
Mapillary imagery filtering broken?

### ISSUE THREAD

**Issue by mvexel** [facebook/Rapid#762]
### Description

Whatever I try, I can't seem to make Rapid apply Mapillary filters I put in. 
Neither the image type (flat / panoramic) or the date filters seem to affect the actual sequences displayed.

Additional nitpick is that the date picker is a little finicky and lets you select dates in the future.

### Version

2.00-alpha.3.3

### What browser are you seeing the problem on? What version are you running?

Firefox v108.0

### The browser URL at the time you encountered the bug

https://mapwith.ai/rapid-v2-alpha3#background=Bing&datasets=fbRoads,msBuildings&disable_features=boundaries&map=20.40/40.75395/-111.83263&photo=mapillary/1477797682563336&photo_overlay=mapillary

**Comment by tsmock** [comment]
> or applying username filters (I'm not sure we get usernames from Mapillary API anymore?)

That is correct. We cannot get usernames from the API. We _can_ get organizations though (`organization_id` in the vector tiles) followed by a call to `https://graph.mapillary.com/:organization_id` (if you want to get a nice name).

**Comment by tordans** [comment]
I suggest to update this issue to "Mapillary image type filter broken".

The date filter works for me ([Testlink](https://rapideditor.org/rapid#background=Berlin-2022&datasets=fbRoads,msBuildings&disable_features=boundaries&map=18.78/52.42197/13.51512&photo=mapillary/494025625174091&photo_dates=2023-01-01_&photo_overlay=mapillary,mapillary-map-features)) but the "show only 360° images" filter does nothing (not even a console error).

**Comment by tsmock** [comment]
@tordans : I _think_ @Bonkles fixed the 360 problem in d1295c73f36e8b261fed775773c27154f3db010d (#955).

If it isn't fully fixed (i.e., some mapillary images that are panographic are being filtered out), it is possible that we might need to add some additional checks, or poke the Mapillary guys.

At one point in time, I had to add some checks against the camera type in the JOSM plugin (pretty much `"spherical" === properties.camera_type || "equirectangular" == properties.camera_type`), but I think that was so that I could tell the image viewer that the image was spherical. The plugin downloads the Mapillary sequence for various reasons (one of which is to try and get a "better" location for the images).

**Comment by Bonkles** [comment]
@tsmock is correct, these filters were fixed in #955. Closing!
