### ISSUE TITLE
[blue sky] change viewer

### ISSUE THREAD

**Issue by mvexel** [facebook/RapiD#774]
### Description

For more advanced users, it would be super neat if you could obtain a visual representation of changes made in your current editing session, like in OSMCha:

![image](https://user-images.githubusercontent.com/120452/215547036-88fe52de-880c-4889-985f-2292d4c0a2da.png)

or Achavi:

![image](https://user-images.githubusercontent.com/120452/215547964-de99f62e-a18b-4045-a1b9-4ffcfc2d8a90.png)

**Comment by Bonkles** [comment]
Hi @mvexel - we have an issue to restore the old 'diff view' that was in v1. That bug is here: [Enable Visual Difference mode#509](https://github.com/facebook/RapiD/issues/509). Are you looking for us to restore that functionality? If so, I will mark this as a duplicate. 

Or- are you asking for something different than the old functionality, and want something more in line with what osmCha does for highlighting changes?

**Comment by mvexel** [comment]
Oh wow, I didn't know that was in Rapid previously. Yes, that looks like what I would like to be able to see. Ideally as part of the pre-upload view.

**Comment by Bonkles** [comment]
Got it! Okay, I will consider this one as a duplicate then and close it. Thanks!
