### ISSUE TITLE
Path styling differences from v1

### ISSUE THREAD

**Issue by Bonkles** [facebook/Rapid#811]
### Description

Paths should be styled differently from footpaths, but in v2 they are showing up as the same. 

Here's a picture of a path and a footpath in v1 (top) and v2 (bottom) 

Paths are on the left, footpaths are on the bottom. 

![image](https://user-images.githubusercontent.com/1887955/219446167-78402041-a0c2-41d1-9d4d-ec0893f6c76a.png)

### Version

2.0.0-beta.0

### What browser are you seeing the problem on? What version are you running?

Chrome v110.0

### The browser URL at the time you encountered the bug

https://mapwith.ai/rapid-v2-beta#background=Bing&datasets=fbRoads,msBuildings&disable_features=boundaries&id=w-6&map=18.70/36.01793/-114.73739

**Comment by bhousel** [comment]
I agree with this specific issue - we should put the "path" style back.  

But - is some of this ok though?  
I don't think people necessarily expect that we'd carry forward every style decision from iD/v1?

Over the years people did push for different colors for things like crossing types or parking aisle types, and it got to be that there were subtle differences between line color styles that nobody really understood (or, color-weak users could even visually distinguish). 

Generally speaking, I'd kind of prefer to reduce the number of distinct styles - maybe just have a few base styles with a different color for if it is special somehow - "service road" vs "special service road" or "footpath" vs "special footpath".  Rather than 5 shades of beige.

**Comment by Bonkles** [comment]
I am in broad agreement that we don't have to feel tied to getting 100% of the styling the same.individual differences like this are not a high priority, but since we made everything else unncannily accurate to how iD/v1 rendered things,  I can see how differences like this would be perceived as a bug or oversight.

**Comment by mvexel** [comment]
I agree as well -- too much fidelity in styling just makes the map data harder to read and will increase the number of visibility edge cases we need to test for (even disregarding various type of color blindness we would need to account for.)

**Comment by bhousel** [comment]
done in #868
