### ISSUE TITLE
No graphical diference between paved and unpaved ways and all its variants

### ISSUE THREAD

**Issue by jjiglesiasg** [facebook/Rapid#820]
### Description

When you draw or is depicted line like a highway=unclassified or highway=track or highway=path there is NO graphical difference if the way is paved or not.

In V1 and ID is a common feature

### Version

2.0.0-beta.0

### What browser are you seeing the problem on? What version are you running?

Chrome v110.0

### The OS you're using

Win10

### Steps to reproduce

Just draw any line as a way and chose the surface tag.

### The browser URL at the time you encountered the bug

https://mapwith.ai/rapid-v2-beta#background=Mapbox&datasets=fbRoads,msBuildings&disable_features=power&id=w309265981&map=15.16/-18.1242/-68.7111

**Comment by jjiglesiasg** [comment]
This seems to be more related to the zoom level used. There are diferences between V1/ID and V2

**Comment by bhousel** [comment]
> This seems to be more related to the zoom level used. There are diferences between V1/ID and V2

Yes, at lower zooms we don't draw the line casings that would indicate whether the surface is paved or not.   
(Also in this location we also dont draw the river direction arrows at low zoom)..  We're using zoom to decide this, but I think eventually we'll get more sophisticated about preparing the scene so that in remote areas we don't have to drop so much detail that we would need to drop in dense urban areas.

https://github.com/facebook/RapiD/issues/557#issuecomment-1220867649 has some more info.

**Comment by bhousel** [comment]
Going to close this , since we actually _are_ showing a visual difference in paved/unpaved surfaces at normal zooms - we just don't show it at low zooms because the casings aren't drawn.  This is because of line drawing inefficiency and it might be resolved once we improve that.
