### ISSUE TITLE
Rapid Suggested data (roads and buildings) should be active by default

### ISSUE THREAD

**Issue by jjiglesiasg** [facebook/Rapid#930]
### Description

When you open Rapid, in V2 you need to select (Toggle) Roads and Buildings, these should be active by default (That's why mainly people came to use Rapid); and if the user do not want to use one or another or any, should deselect such features in the RapID select button.

### Version

2.0.2

### What browser are you seeing the problem on? What version are you running?

Chrome Version 105.0.5195.127 (Official Build) (64-bit)

### Steps to reproduce

You just open Rapid V.2 in any Chrome or Edge browser

### The browser URL at the time you encountered the bug

https://mapwith.ai/rapid#background=Maxar-Premium&datasets=fbRoads,msBuildings&disable_features=boundaries&map=18.00/-14.76062/-68.43293
![Screenshot 2023-04-24 14 01 49](https://user-images.githubusercontent.com/22849578/234079773-9b9282cb-5b94-41f7-8b7d-d2bdbdab3a21.png)

**Comment by gyCfjSnO** [comment]
I support this idea. I had to figure out what was so different between Rapid & OSM editor before I figured out how to enable the Rapid Assist 'layers'.

**Comment by bhousel** [comment]
Oh yeah I will fix this - sorry it is taking a few months.
I've been doing a bunch of core refactoring work that should make the startup process a lot easier to reason about.

The root cause that these datasets were unchecked was because of a race condition when working with the url hash.
(e.g. Rapid tries to set the hash to say what datasets are active, but also tries to read the hash to know what datasets should be active).  Going forward we're going to be more strict about when things happen as the application starts.
