### ISSUE TITLE
Help section references iD Editor

### ISSUE THREAD

**Issue by tordans** [facebook/Rapid#995]
### Description

The help section references iD and links to the iD Repo, not Rapid

<img width="615" alt="image" src="https://github.com/facebook/Rapid/assets/111561/d1cf856b-4bb8-4ed5-82b5-f71e9105d2d7">

### Version

2.0.3

### What browser are you seeing the problem on? What version are you running?

Chrome

### The browser URL at the time you encountered the bug

https://rapideditor.org/rapid#background=EsriWorldImagery&datasets=fbRoads,msBuildings&map=2.00/0.0/0.0

**Comment by bhousel** [comment]
Oh yeah this is because of localization data 😞 

In the source language (en.json) it looks correct:
<img width="400" alt="Screenshot 2023-07-28 at 7 46 33 AM" src="https://github.com/facebook/Rapid/assets/38784/3e670519-1248-4ff1-ac79-c61203efbf06">

But we're still reusing the localizations files from the iD project, so they can be wrong when using another language, for any string that is different from the iD string.  

We have issue #206 for this - I feel like the challenge is probably more significant than the wording on that issue indicates.
